# Project information
site_name: Cisco ACI Guide
site_description: Guia Cisco ACI
site_author: Weslley Silva
site_url: https://infra.expert/cisco_aci

# Repository
repo_name: weslleycsil/estudos-certificacoes
repo_url: https://github.com/weslleycsil/estudos-certificacoes/tree/main/cisco/cisco_aci

# Copyright
copyright: Weslley Silva &copy; 2024

# Configuration
theme:
  name: material
  language: pt-BR
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/weslleycsil
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/weslleycsil

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true